language: cpp
env:
  matrix:
  - ARCH=
  - ARCH=i386
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  # LATER: shouldn't this be set via env-variable in the webinterface for
  # travis-ci?
  - secure: apX0Luqzl0ggMxDK8VffpG1smqLUy41dtMew+bPCbTEkZW8u5qBzLJzeOxMUJdgivpUcJGQYccpqfvvJxDHWQYdUZwMP3WLy64LxzmSppbPXqqp3wdHfWUfffGc7h37I/KLMAeJaZeJyvpRghfahgUwaIB1bJKAzAhlEbL82aLw=

## 'os' selection needs to be enabled manually by emailing travis-ci
os:
  - linux
  - osx


matrix:
  exclude:
   - os: linux
     env: ARCH=i386

before_install:
- "./build/travis-ci/depinstall.sh"
script:
- "./build/travis-ci/build.sh"

## deploy disabled until i have fixed github/releases
 before_deploy:
 - "./build/travis-ci/prepare-upload.sh"
 deploy:
   provider: releases
   api_key:
     secure: mW3u93mi2ZFXB3u32+/LWcePBPwhSE5k/MvrxVnM3i1bgwMK//+7V9enJAmL645LWQyBtUz5q7Jv5m2Vk1W4xd9j0j/hI/QchblPfok1Mo8TcCdnyCgbUvjIJwP+5X0d4ALscn7rYzPxxtEvLrXRLc6IXqYRpCl9tBjOOCM9ysY=
   file: Gem-${TRAVIS_COMMIT}.tgz
   on:
     repo: umlaeute/Gem
     tags: true
     all_branches: true

addons:
  coverity_scan:
    project:
      name: umlaeute/Gem
      description: Build submitted via Travis CI
    notification_email: pd-gem-CVS@lists.sourceforge.net
    build_command_prepend: "./autogen.sh && ./configure && make clean"
    build_command: make -j 4
    branch_pattern: coverity_scan
